[k3s]
k3s_node ansible_host=127.0.0.1 ansible_port=2222 internal_ip=192.168.56.5 ansible_ssh_private_key_file=C:/devops-tp-final/.vagrant/machines/k3s/virtualbox/private_key

[monitoring]
monitoring_node ansible_host=127.0.0.1 ansible_port=2200 internal_ip=192.168.56.6 ansible_ssh_private_key_file=C:/devops-tp-final/.vagrant/machines/monitoring/virtualbox/private_key

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
