name: CI/CD Pipeline TP Final
on:
  push:
    branches:
      - main
jobs:
  deploiement:
    runs-on: self-hosted
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4
      - name: Préparation des permissions
        run: chmod +x deploy.sh
      - name: Exécution du déploiement
        run: ./deploy.sh
